import { ReactNode } from "react";

export const metadata = {
  title: "Messages",
  description: "Generated by create next app",
};

export interface LayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: Readonly<LayoutProps>) {
  return children;
}
